Repository Team-useMemo/Jugger-Backend, pull requests merged in 2025-05, with the labels that each got.

#58 feat : 소셜 로그인 구현
  build.gradle
  src/main/java/com/usememo/jugger/domain/user/entity/User.java
  src/main/java/com/usememo/jugger/domain/user/repository/UserRepository.java
  src/main/java/com/usememo/jugger/global/config/SecurityConfig.java
  src/main/java/com/usememo/jugger/global/exception/ErrorCode.java
  src/main/java/com/usememo/jugger/global/exception/GlobalExceptionHandler.java
  src/main/java/com/usememo/jugger/global/security/CustomOAuth2User.java
  src/main/java/com/usememo/jugger/global/security/CustomOAuth2UserService.java
  src/main/java/com/usememo/jugger/global/security/JwtTokenProvider.java
  src/main/java/com/usememo/jugger/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/usememo/jugger/global/security/token/controller/AuthController.java
  src/main/java/com/usememo/jugger/global/security/token/domain/KakaoOAuthProperties.java
  src/main/java/com/usememo/jugger/global/security/token/domain/KakaoUserResponse.java
  src/main/java/com/usememo/jugger/global/security/token/domain/RefreshToken.java
  src/main/java/com/usememo/jugger/global/security/token/domain/TokenResponse.java
  src/main/java/com/usememo/jugger/global/security/token/repository/RefreshTokenRepository.java
  src/main/java/com/usememo/jugger/global/security/token/service/KakaoOAuthService.java
Labels: FEATURE

#61 feat: 카테고리 핀 설정,해제 API
  src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java
  src/main/java/com/usememo/jugger/domain/category/entity/Category.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryService.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java
  src/main/java/com/usememo/jugger/global/config/ReactiveMongoConfig.java
  src/main/java/com/usememo/jugger/global/config/SecurityConfig.java
  src/main/java/com/usememo/jugger/global/security/token/controller/AuthController.java
Labels: REFACTOR

#60 refactor: swagger cors, 채팅 로직 수정
  src/main/java/com/usememo/jugger/JuggerApplication.java
  src/main/java/com/usememo/jugger/domain/calendar/entity/Calendar.java
  src/main/java/com/usememo/jugger/domain/chat/dto/GetChatByCategoryDto.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/link/entity/Link.java
  src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java
Labels: REFACTOR

#66 refactor : 카카오 로그인 수정
  build.gradle
  src/main/java/com/usememo/jugger/domain/user/entity/User.java
  src/main/java/com/usememo/jugger/global/exception/ErrorCode.java
  src/main/java/com/usememo/jugger/global/security/JwtTokenProvider.java
  src/main/java/com/usememo/jugger/global/security/token/controller/AuthController.java
  src/main/java/com/usememo/jugger/global/security/token/domain/KakaoLoginRequest.java
  src/main/java/com/usememo/jugger/global/security/token/domain/KakaoUserResponse.java
  src/main/java/com/usememo/jugger/global/security/token/service/KakaoOAuthService.java
Labels: FIX

#67 [FEAT] 사용자 로직 추가
  build.gradle
  src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryService.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java
  src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/health/controller/HealthController.java
  src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java
  src/main/java/com/usememo/jugger/domain/photo/service/PhotoService.java
  src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java
  src/main/java/com/usememo/jugger/global/config/SecurityConfig.java
  src/main/java/com/usememo/jugger/global/security/JwtAuthenticationConverter.java
  src/main/java/com/usememo/jugger/global/security/JwtAuthenticationManager.java
  src/main/java/com/usememo/jugger/global/security/JwtTokenProvider.java
  src/main/java/com/usememo/jugger/global/security/OAuth2AuthenticationSuccessHandler.java
  src/test/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementationTest.java
  src/test/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementationTest.java
  src/test/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementationTest.java
Labels: FEATURE

#70 refactor: filter에 non session 방식 설정
  src/main/java/com/usememo/jugger/global/config/SecurityConfig.java
Labels: REFACTOR

#74 feat: swagger auth token 설정 추가
  src/main/java/com/usememo/jugger/global/config/CorsConfig.java
  src/main/java/com/usememo/jugger/global/config/SwaggerConfig.java
Labels: FIX
