Repository Team-useMemo/Jugger-Backend, pull requests merged in 2025-04, with the labels that each got.

#12 feat: ci/cd 설정
  .github/workflows/deploy.yml
  Dockerfile
Labels: CI/CD

#18 feat : health 체크를 하기 위한 API 추가입니다. #16
  .github/workflows/deploy.yml
  src/main/java/com/usememo/jugger/domain/health/controller/HealthController.java
Labels: CI/CD

#11 feat: 채팅입력 API 개발
  src/main/java/com/usememo/jugger/domain/calendar/entity/Calendar.java
  src/main/java/com/usememo/jugger/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryService.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java
  src/main/java/com/usememo/jugger/domain/chat/dto/GetChatTypeDto.java
  src/main/java/com/usememo/jugger/domain/chat/dto/PostChatDto.java
  src/main/java/com/usememo/jugger/domain/chat/entity/Chat.java
  src/main/java/com/usememo/jugger/domain/chat/entity/ChatType.java
  src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/link/entity/Link.java
  src/main/java/com/usememo/jugger/domain/link/repository/LinkRepository.java
  src/main/java/com/usememo/jugger/domain/photo/repository/PhotoRepository.java
  src/main/java/com/usememo/jugger/domain/user/service/UserService.java
  src/main/java/com/usememo/jugger/global/exception/BaseException.java
  src/main/java/com/usememo/jugger/global/exception/ErrorCode.java
  src/main/java/com/usememo/jugger/global/exception/category/CategoryExistException.java
  src/main/java/com/usememo/jugger/global/exception/chat/CategoryNullException.java
  src/test/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementationTest.java
  src/test/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementationTest.java
Labels: FEATURE

#21 feat: 전체채팅 조회
  src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java
  src/main/java/com/usememo/jugger/domain/chat/dto/GetChatByCategoryDto.java
  src/main/java/com/usememo/jugger/domain/chat/entity/Chat.java
  src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/main/java/com/usememo/jugger/global/config/MongoAuditingConfig.java
  src/main/java/com/usememo/jugger/global/utils/BaseTimeEntity.java
  src/test/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementationTest.java
Labels: FEATURE

#23 feat : S3 버킷 등록
  .gitignore
  build.gradle
  src/main/java/com/usememo/jugger/global/exception/ErrorCode.java
  src/main/java/com/usememo/jugger/global/exception/s3/S3UploadException.java
  src/main/java/com/usememo/jugger/global/s3/controller/S3Controller.java
  src/main/java/com/usememo/jugger/global/s3/service/S3Service.java
  src/main/java/com/usememo/jugger/global/s3/service/S3ServiceImplementation.java
  src/main/resources/application.yml
  src/test/java/com/usememo/jugger/global/s3/service/S3ServiceImplementationTest.java
Labels: FEATURE, V1

#22 feat: 링크입력 v1
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/link/entity/Link.java
  src/test/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementationTest.java
Labels: FEATURE

#38 feat: 링크조회 API 개발
  src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java
  src/main/java/com/usememo/jugger/domain/link/controller/LinkController.java
  src/main/java/com/usememo/jugger/domain/link/dto/GetLinkDto.java
  src/main/java/com/usememo/jugger/domain/link/entity/Link.java
  src/main/java/com/usememo/jugger/domain/link/repository/LinkRepository.java
  src/main/java/com/usememo/jugger/domain/link/service/LinkService.java
  src/main/java/com/usememo/jugger/domain/link/service/LinkServiceImplementation.java
  src/main/resources/application.yml
  src/test/java/com/usememo/jugger/domain/link/service/LinkServiceImplementationTest.java
Labels: FEATURE

#31 feat: 카테고리별 채팅 조회
  .gitignore
  src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java
  src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java
  src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/test/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementationTest.java
Labels: FEATURE

#45 feat : 사진들 get 구현
  src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java
  src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoDto.java
  src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoRequestDto.java
  src/main/java/com/usememo/jugger/domain/photo/dto/PhotoDto.java
  src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java
  src/main/java/com/usememo/jugger/domain/photo/repository/PhotoRepository.java
  src/main/java/com/usememo/jugger/domain/photo/service/PhotoService.java
  src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java
  src/main/java/com/usememo/jugger/global/s3/controller/S3Controller.java
  src/main/java/com/usememo/jugger/global/s3/service/S3Service.java
  src/main/java/com/usememo/jugger/global/s3/service/S3ServiceImplementation.java
  src/test/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementationTest.java
  src/test/java/com/usememo/jugger/global/s3/service/S3ServiceImplementationTest.java
Labels: FEATURE

#52 refactor : 사진 post 기능 수정
  src/main/java/com/usememo/jugger/global/s3/controller/S3Controller.java
Labels: REFACTOR

#51 refactor : photo get 관련해서 수정
  src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java
  src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoDto.java
  src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoRequestDto.java
  src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java
  src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java
  src/test/java/com/usememo/jugger/domain/calendar/service/CalendarServiceImplementationTest.java
  src/test/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementationTest.java
Labels: REFACTOR

#50 feat : CORS 설정 추가
  src/main/java/com/usememo/jugger/global/config/CorsConfig.java
Labels: FEATURE

#55 feat: swagger 추가
  build.gradle
  src/main/java/com/usememo/jugger/domain/calendar/controller/CalendarController.java
  src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java
  src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java
  src/main/java/com/usememo/jugger/domain/health/controller/HealthController.java
  src/main/java/com/usememo/jugger/domain/link/controller/LinkController.java
  src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java
  src/main/java/com/usememo/jugger/global/config/SwaggerConfig.java
Labels: FEATURE

#56 refactor: 카테고리 조회 로직 수정
  src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java
  src/main/java/com/usememo/jugger/domain/category/dto/GetRecentCategoryDto.java
  src/main/java/com/usememo/jugger/domain/category/entity/Category.java
  src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryService.java
  src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java
  src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java
  src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java
  src/test/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementationTest.java
Labels: REFACTOR
